import "@/app/globals.css";
import { AppSidebar } from "@/components/common/app-sidebar";
import Header from "@/components/ui/header";
import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`} style={{ background: "#333", color: "#fafafa" }}>
        <SidebarProvider>
          <div className="h-screen w-full">
            <Header />
            <div className="flex flex-1 min-h-0">
              <AppSidebar className="top-16" />
              <main className="flex-1 overflow-auto py-4 p-8">{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
