name: Deploy Web App to DLB (EC2)

on:
  push:
    branches: [dev, main]

jobs:
  deploy:
    runs-on: [self-hosted, dlb, web]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy app
        working-directory: /opt/dlb/web
        env:
          DLB_TOKEN: ${{ secrets.DLB_TOKEN }}
        run: |
          set -e
          BRANCH="${{ github.ref_name }}"

          if [ "$BRANCH" = "main" ]; then
            COMPOSE_FILE="docker/compose.production.yml"
          else
            COMPOSE_FILE="docker/compose.uat.yml"
          fi

          echo "🔁 Deploying branch $BRANCH using $COMPOSE_FILE"

          # Make sure on the correct branch
          git checkout $BRANCH

          # Pull latest changes
          git pull origin $BRANCH

          echo "🐳 Building image"
          docker compose -f $COMPOSE_FILE build

          echo "🚀 Restarting container"
          docker compose -f $COMPOSE_FILE up -d
